### ISSUE TITLE
Lockscreen clock font not changed

### ISSUE THREAD

**Issue by maliknajeeb133** [Magisk-Modules-Repo/Magisk_Font_Bellota#10]
Bro... I tried this module..... This font is great but on lockscreen the clock font is not changed 🤔.... Don't know why... With previous versions it was working fine... But with 1.9 update it won't change lockscreen clock font.....
I'm using Android lollipop 5.1 .....
I tried it with other phones also but same result

**Comment by pirasalbe** [comment]
Hi, can you tell me your module list??
And can you send me Magisk log??
