### ISSUE TITLE
not working...

### ISSUE THREAD

**Issue by rakbar650** [Magisk-Modules-Repo/Magisk_Font_Bellota#11]
Device redmi note 4 a.k.a nikel

**Comment by pirasalbe** [comment]
Hi, can you explain it better??
You can't install it or you can but it doesn't change your font??

**Comment by rakbar650** [comment]
I dan install but itu first apply on all apps... Only inside apps... But
you like status bar... Launcher... And lock screen... Itu still remain
stocking font...

Pada tanggal 20 Jan 2018 16.15, "pirasalbe" <notifications@github.com>
menulis:

**Comment by pirasalbe** [comment]
I don't know, which rom do you use and what android version?
