### ISSUE TITLE
Android lock screen clock glitch

### ISSUE THREAD

**Issue by nickpufferfish** [Magisk-Modules-Repo/Magisk_Font_Bellota#3]
Android version: Oreo (8.0.0)
Phone model: Oneplus 2

Everything seems to be working fine except for the lock screen clock display with the colon (:). No errors during installation. Overall, great module! Hope you can find a fix for this. 

![screenshot_20171009-131600](https://user-images.githubusercontent.com/17262068/31351110-d53a22cc-acf7-11e7-9c2a-7057416f3de4.png)

**Comment by pirasalbe** [comment]
Hi, I've tried some fix but none of them worked
Plus, I don't have a phone with Oreo so I'm not able to test it properly. I'll fix this as soon as I'm able to find a rom with Oreo and free time
Thanks for your patient

**Comment by nickpufferfish** [comment]
Ok, thanks for looking into the issue.

**Comment by pirasalbe** [comment]
Hi, I've pushed an update with a fallback (the font that fix this issue in the other android versions) from Android Oreo.
I'm not sure if it fixes your bug but if it does let me know. Thank you!

**Comment by pirasalbe** [comment]
I've fixed this bug on Android Oreo in the last update :)

**Comment by nickpufferfish** [comment]
Thanks! I installed the latest version and can confirm it is indeed fixed.

**Comment by LokeYourLord** [comment]
@pirasalbe How did you fix the issue? I would like to do that with the Bahnschrift Font from Windows 10 that I now use on my Phone, but I am also experiencing this issue :/ Thanks in advance!

**Comment by LokeYourLord** [comment]
I am able to edit the font, but I want to know what was missing from the font file that Roboto (or on Windows SegoeUI) has, like what is the character that was missing called, as I have the same issue in Windows 10 when using Bahnschrift as my System Font for the clock and such.

**Comment by pirasalbe** [comment]
I changed source of font, I found it more complete

**Comment by pirasalbe** [comment]
But if you want to edit the font just add the colon on U+EE01

**Comment by LokeYourLord** [comment]
Ah yes that was the thing I was looking for, thanks a lot :D!
