### ISSUE TITLE
Product Sans Font Request

### ISSUE THREAD

**Issue by DallasBelt** [Magisk-Modules-Repo/Magisk_Font_Bellota#4]
I was wondering if you could make another module to replace system font with the Google Product Sans one. Thanks!

**Comment by pirasalbe** [comment]
Did you mean something like [this](https://github.com/Magisk-Modules-Repo/google-sans-enabler)??

**Comment by DallasBelt** [comment]
I tried that module but it doesn't replace the system font (yours does). It just adds the font files to /system/fonts to apply them later with an app, I guess.

**Comment by pirasalbe** [comment]
I will try something as soon as I've free time :)

**Comment by DallasBelt** [comment]
Cool! That'd be awesome :D

**Comment by pirasalbe** [comment]
I did something.
Have a look [here](https://github.com/pirasalbe/Magisk_Font_Google), if you need more help you can also contact me on Telegram
