### ISSUE TITLE
DroidSansFallback.ttf is not used in config.sh

### ISSUE THREAD

**Issue by sharukhmohammed** [Magisk-Modules-Repo/Magisk_Font_Bellota#5]
### DroidSansFallback.ttf is present as a file but it is not added to config.sh.

REPLACE="
/system/fonts/AndroidClock.ttf
**this is missing**
`/system/fonts/DroidSansFallback.ttf`
/system/fonts/Roboto-Black.ttf
/system/fonts/Roboto-BlackItalic.ttf
/system/fonts/Roboto-Bold.ttf
/system/fonts/Roboto-BoldItalic.ttf
/system/fonts/RobotoCondensed-Bold.ttf
/system/fonts/RobotoCondensed-BoldItalic.ttf
/system/fonts/RobotoCondensed-Italic.ttf
/system/fonts/RobotoCondensed-Light.ttf
/system/fonts/RobotoCondensed-LightItalic.ttf
/system/fonts/RobotoCondensed-Regular.ttf
/system/fonts/Roboto-Italic.ttf
/system/fonts/Roboto-Light.ttf
/system/fonts/Roboto-LightItalic.ttf
/system/fonts/Roboto-Medium.ttf
/system/fonts/Roboto-MediumItalic.ttf
/system/fonts/Roboto-Regular.ttf
/system/fonts/Roboto-Thin.ttf
/system/fonts/Roboto-ThinItalic.ttf
"

**Comment by pirasalbe** [comment]
I know, it is not used because it is not already in your phone so I don't have to replace it
Which android version are you using?? 
Have you got issue with colon in the lock screen??
If yes does this change fix your problem??

**Comment by pirasalbe** [comment]
Anyway I tried adding that line ([test.zip](https://github.com/Magisk-Modules-Repo/Magisk_Font_Bellota/files/1459095/test.zip))

Here are the screenshots
File from magisk -> ![original](https://user-images.githubusercontent.com/4697821/32628330-cbb0f968-c595-11e7-990c-76dda74bc43c.png)
File with your suggestion -> ![new](https://user-images.githubusercontent.com/4697821/32628332-cbd8071a-c595-11e7-8424-f1e4164a20ba.png)

As you can see there are no difference as I said before. If you have any issue please tell me :)

**Comment by sharukhmohammed** [comment]
I currently am on a _Custom 7.1.1 ROM(Ressurection Remix)_. However, it is based on _AOSP_, it wouldn't matter much.
I faced no issues with lock screen clock font too. I guess you should **remove it from /system/fonts if you don't use it with the module to reduce redundancy.** 
Just my suggestion though. I don't have any Oreo device to test on.
Completely by off topic, it doesn't support **Bold** and _Italic_ faces.

**Comment by pirasalbe** [comment]
Yes, it does support them.
Anyway DroidSansFallback is needed, if you try removing it you'll see that the colon in the lock screen is bugged. 
It is not needed in config.sh because there you place only the things you need to replace, not the thing that you add to the system

**Comment by pirasalbe** [comment]
Can you tell me where you don't see bold and italic??

**Comment by sharukhmohammed** [comment]
Sorry man, my bad. It does. Cheers.

**Comment by pirasalbe** [comment]
Thanks. Cheers
